4_Django/coderslab/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from homework import views as homework_views
from exercises import views as exercise_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path("movies/", homework_views.show_movies),
    path("movie_detail/<int:id>", homework_views.show_movie_detail),
    path("show_band/<int:id>", exercise_views.show_band),
    path("tm/", exercise_views.tabliczka_mnozenia),
    path("przywitanie/", exercise_views.imie),
    path('temp/', exercise_views.temp),
    path('show_session/', exercise_views.show_session),
    path('set_session/', exercise_views.set_session),
    path('del_session/', exercise_views.del_session),
    path('del_session/', exercise_views.del_session),
    path('edit_person/<int:id>', homework_views.edit_person),
    path('edit_movie/<int:id>', homework_views.edit_movie)
]

4_Django/exercises/models.py
from django.db import models

GENRE = (
    (-1, 'fasdfasdfasd'),
    (0, 'POP' ),
    (1, 'rock')
)
# Create your models here.
class Band(models.Model):
    name = models.CharField(max_length=64)
    year = models.IntegerField(null=True)
    still_active = models.BooleanField(default=True)
    genre = models.IntegerField(choices=GENRE, default=-1)

    def __str__(self):
        return self.name+" "+ str(self.year)
RATING = (
    (1,'BAD'),
    (2,'NOT SO BAD'),
    (3,'EEE'),
    (4,'GOOD'),
    (5,'VERY GOOOOOD'),
)
class Album(models.Model):
    title = models.CharField(max_length=124)
    year = models.IntegerField()
    rating = models.IntegerField(choices=RATING)
    band = models.ForeignKey(Band, on_delete=models.DO_NOTHING)


album_rating=(
    (0,"one"),
    (1,'two'),
    (2, 'smash'),
    (3, 'overwatch'),
    (4, '')
)

4_Django/football/models.py
from django.db import models

# Create your models here.

4_Django/homework/models.py
from django.db import models

class Person(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)

class Genre(models.Model):
    name = models.TextField()

class Movie(models.Model):
    title = models.CharField(max_length=128)
    director = models.ForeignKey(Person, on_delete=models.DO_NOTHING, related_name='dirctor')
    screenplay = models.ForeignKey(Person, on_delete=models.DO_NOTHING, related_name='screen_play')
    starring = models.ManyToManyField(Person, related_name='actor', through='PersonMovie')
    year = models.IntegerField()
    rating = models.FloatField()
    genre = models.ManyToManyField(Genre)

class PersonMovie(models.Model):
    actor = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    role = models.CharField(max_length=128)

4_Django/exercises/views.py
from exercises.models import Band
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from exercises.temperature_functions import oblicz_celc_to_fahr, oblicz_fahr_to_celc

def show_band(request, id):
    band = Band.objects.get(id=id)

    return render(request, 'show_band.html', {'band': band})


def tabliczka_mnozenia(request):
    height = int(request.GET['height'])
    width = int(request.GET['width'])
    ret_list = []
    for i in range(1,height+1):
        temp_list = []
        for j in range(1,width+1):
            temp_list.append(i*j)
        ret_list.append(temp_list)
    return render(request, 'tm.html', {'tm':ret_list})


@csrf_exempt
def imie(request):
    if request.method == 'GET':
        html = """
        <form method = 'post'>
        imie:<input type='text' name='name'>
        nazwisko:<input type='text' name='last_name'>
        <input type='submit' value='go go go reko gadgeta'>
        """
        return HttpResponse(html)
    else:
        name = request.POST['name']
        ln = request.POST["last_name"]
        return HttpResponse(f'witaj {name} {ln}!!! ')

@csrf_exempt
def temp(request):
    if request.method == 'POST':
        degrees = float(request.POST['degrees'])
        direction = request.POST['convertionType']
        if direction == 'celcToFahr':
            ret_val = f'celcjusz {degrees}  to Fahr {oblicz_celc_to_fahr(degrees)}'
        else:
            ret_val = f'fahr {degrees}  to celc {oblicz_fahr_to_celc(degrees)}'
        return HttpResponse(ret_val)
    else:
        return render(request, 'temp.html')


def show_session(request):
    if 'counter' in request.session:
        request.session['counter']+=1
        return HttpResponse (f"jupika jej zmienna counter = {request.session['counter']}")
    return HttpResponse("zmienna counter nie istneje")


def set_session(request):
    request.session['counter'] = 1
    request.session['sadfkldsajhf'] = 'dupa'
    return HttpResponse("udało sie ustawić sessje")

def del_session(request):
    del request.session['counter']
    return HttpResponse("udało sie skasować sessje")


def show_cookie(request):
    if 'counter' in request.cookie:
        request.session['counter']+=1
        return HttpResponse (f"jupika jej zmienna counter = {request.session['counter']}")
    return HttpResponse("zmienna counter nie istneje")


def set_session(request):
    request.session['counter'] = 1
    request.session['sadfkldsajhf'] = 'dupa'
    return HttpResponse("udało sie ustawić sessje")

def del_session(request):
    del request.session['counter']
    return HttpResponse("udało sie skasować sessje")

4_Django/football/views.py
from django.shortcuts import render

# Create your views here.

4_Django/homework/views.py
from django.shortcuts import render
from homework.models import Movie, PersonMovie, Person, Genre
# Create your views here.

def get_sort_by_key(id):
    temp_dict = {'1': 'rating',
     '2': '-rating',
     '3': 'year'
    }
    return temp_dict[id]

def show_movies(request):
    key = request.session.get('key', '3')
    key = request.GET.get('key', key)
    request.session['key'] = key
    movies = Movie.objects.all().order_by(get_sort_by_key(key))
    return render(request, 'movies.html', {"movies":movies})

def show_movie_detail(request, id):
    movie = Movie.objects.get(id=id)
    actorsMovies = PersonMovie.objects.filter(movie = movie)
    return render(request, 'movie_detail.html', {"movie": movie, 'sttaring':actorsMovies})


def edit_person(request, id):
    id = request.POST.get('id', id)
    person = Person.objects.get(id=id)
    if request.method == "POST":
        person.first_name = request.POST['first_name']
        person.last_name = request.POST['last_name']
        person.save()
    return render(request, 'edit_person.html', {'person': person})

def edit_movie(request, id):
    id = request.POST.get('id', id)
    movie = Movie.objects.get(id=id)
    genre  = Genre.objects.all()

    if request.method == "POST":
        selected = request.POST.getlist('genre')
        movie.title = request.POST['title']
        movie.year = request.POST['year']
        g = Genre.objects.filter(id__in=selected)
        movie.genre.set(g)
        movie.save()
    return render(request, 'edit_movie.html', {'movie': movie, 'genre':genre})

4_Django/exercises/templates/temp.html
<form  method="POST">
    <label>
        Temperatura:
        <input type="number" min="0.00" step="0.01" name="degrees" value=34>
    </label>
    <input type="submit" name="convertionType" value="celcToFahr">
    <input type="submit" name="convertionType" value="FahrToCelc">
</form>

4_Django/exercises/templates/tm.html
<table>
    <tr>
        <th></th>
        {% for item in tm.0 %}
            <th>{{ item }}</th>
        {% endfor %}
    </tr>
    {% for line in tm %}
        <tr>
            <th>{{ line.0 }}</th>
            {% for item in line %}
                <td>{{ item }}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>

4_Django/homework/templates/edit_movie.html
<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ movie.id }}">
    <input type="text" name="title" value="{{ movie.title }}">
    <input type="number" name="year" value="{{ movie.year }}">
    <select multiple name="genre">
        {% for g in genre %}
            <option value="{{ g.id }}"
                    {% if g in movie.genre.all %}selected{% endif %}>
                {{ g.name }}</option>
        {% endfor %}
    </select>
    <button type="submit">zmień</button>
</form>

4_Django/homework/templates/edit_person.html
<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ person.id }}">
    <input type="text" name="first_name" value="{{ person.first_name }}">
    <input type="text" name="last_name" value="{{ person.last_name }}">
    <button type="submit">zmień</button>
</form>

4_Django/homework/templates/movie_detail.html
<strong>Tytuł: {{ movie.title }}</strong><br>
scenariusz: {{ movie.screenplay.first_name }} {{ movie.screenplay.last_name }}<br>
rezyser: {{ movie.director.first_name }} {{ movie.director.last_name }}<br>
gatunek:
{%   for genre in movie.genre.all %}
    {{ genre.name }}<br>
{% endfor %}
{% for item in sttaring %}
    {{ item.actor.first_name }} {{ item.actor.last_name }} w roli {{ item.role }}
{% endfor %}

4_Django/homework/templates/movies.html
<a href="/movies?key=1">rosnaco</a>
<a href="/movies?key=2">malejaco</a>
<a href="/movies?key=3">rok</a>


<ul>
{% for movie in movies %}
    <li><a href="/movie_detail/{{movie.id}}">{{ movie.title }}</a></li>
{% endfor %}
</ul>

4_Django/homework/templates/show_band.html
nazwa:{{ band.name }}<br>
aktywny:{{ band.still_active }}<br>
rok założenia:{{ band.year }}<br>
gatunek: {{ band.get_genre_display }}<br>


{% for album in band.album_set.all %}
    -----------------<br>
    {{ album.title }}<br>
    {{ album.year }}<br>
    {{ album.get_rating_display }}<br>
{% endfor %}